name: renamery
description: Flutterを使用したNameryファイルリネームツールの復活版。
publish_to: 'none'
version: 0.11.2+12

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # 状態管理
  provider: ^6.1.1
  
  # ファイルとパスのユーティリティ
  path: ^1.9.0
  
  # オプション: 後でファイルピッカーが必要になった場合
  file_selector: ^1.0.3
  multi_split_view: ^3.6.1
  path_provider: ^2.1.5
  window_manager: ^0.5.1

  shared_preferences: ^2.3.2
  intl: ^0.20.0
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  url_launcher: ^6.3.0
  windows_single_instance: ^1.1.0
  win32: ^5.15.0
  ffi: ^2.1.2
  material_symbols_icons: ^4.2906.0
  package_info_plus: ^8.0.0
  super_clipboard: ^0.8.4
  flutter_svg: ^2.2.4
  printing: ^5.14.3
  archive: ^4.0.9
  permission_handler: ^11.3.1
  upgrader: ^10.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.14.3
  msix: ^3.16.12

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icon/
    - CHANGELOG.md

flutter_launcher_icons:
  image_path: "assets/icon/app_icon.png"
  android: true
  # Android アダプティブアイコン（背景と前景の分離）設定を追加
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  linux: true
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
    icon_size: 48

msix_config:
  display_name: ReNamery
  publisher_display_name: Toyo Craft Lab
  identity_name: ToyoCraftLab.ReNamery
  publisher: "CN=ToyoCraftLab"
  msix_version: 0.11.2.0
  logo_path: assets/icon/app_icon.png
  store: true
